linters:
  enable-all: true
  disable:
    - mnd
    - godox
    - forbidigo
    - exportloopref
linters-settings:
  gosmopolitan:
    escape-hatches:
      - 'fmt.Printf'
      - 'fmt.Println'
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - disableStutteringCheck
          - checkPublicInterface
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/takanakahiko/furusato/internal
