version: "2"
linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - godox
    - mnd
    - wsl # deprecated (replaced by wsl_v5)
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - exhaustruct
          - funlen
          - gosmopolitan
  settings:
    gosmopolitan:
      escape-hatches:
        - fmt.Printf
        - fmt.Println
    varnamelen:
      ignore-names:
        - tt
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
